[project]
name = "epfl-ml2024-proj-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.1",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
]
